[workspace]
members = [".", "sim", "az"]
resolver = "3"

[workspace.dependencies]
rand = "0.10"

[package]
name = "catan"
version = "0.1.0"
edition = "2024"

[features]
cuda = ["burn/cuda"]

[dependencies]
catan-sim = { path = "sim" }
az = { path = "az" }
rand = { workspace = true }
rand_chacha = "0.10.0"
mimalloc = { version = "0.1", default-features = false }
burn = { version = "0.20", default-features = false, features = [
    "std",
    "autodiff",
    "ndarray",
    "fusion",
    "autotune",
] }
wandb = { git = "https://github.com/NousResearch/wandb-rs", branch = "main" }
tokio = { version = "1", features = ["rt-multi-thread"] }

[target.'cfg(target_os = "macos")'.dependencies]
burn = { version = "0.20", default-features = false, features = ["metal"] }

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
burn = { version = "0.20", default-features = false, features = ["vulkan"] }
